### ISSUE TITLE
Support Italian Language

### ISSUE THREAD

**Issue by ThePirate42** [WarenGonzaga/wifi-passview#13]
When I run the automatic mode, creds.txt doesn't contains password:
```
SSID: : Casa    
# ================================================  
# ================================================  
# Key content is the password of your target SSID.  
# ================================================  
```
Reading older issues makes me think this is probably a localization problem. What should I do?

**Comment by WarenGonzaga** [comment]
Hi @ThePirate42, yes you're right! This issue is based on locale. I haven't implemented the language feature but that's my plan. I'll include your locale for future updates. Thank you for reporting.

**Comment by WarenGonzaga** [comment]
Hi, @ThePirate42 check issue #14 I'm closing this. thank you!
