### ISSUE TITLE
Does it require admin permissions for it to work on win7 ?

### ISSUE THREAD

**Issue by minanagehsalalma** [WarenGonzaga/wifi-passview#2]

**Comment by WarenGonzaga** [comment]
Hi @minanagehsalalma yes it requires permissions to work

**Comment by minanagehsalalma** [comment]
> Hi @minanagehsalalma yes it requires permissions to work

@WarenGonzaga but why ? It works on win 8 and 10 without it .... 
Is this for all commands or just the export or command ? 
Does doing it one network by one manually fixes it ?

**Comment by WarenGonzaga** [comment]
@minanagehsalalma it works well in Windows 8 and 10 but I'm not sure in Windows 7... I will try it on my VM if it will work... I guess there is a command in the program that is unknown to Windows 7.

**Comment by minanagehsalalma** [comment]
Okay ... Try it and tell me.

**Comment by WarenGonzaga** [comment]
@minanagehsalalma I detected the issue working on a fix...

**Comment by minanagehsalalma** [comment]
What was it ?

**Comment by WarenGonzaga** [comment]
@minanagehsalalma the way how it checks for admin privileges...

**Comment by minanagehsalalma** [comment]
So would it still require admin privileges to work ?

**Comment by WarenGonzaga** [comment]
@minanagehsalalma it should be run in admin state... since some part of the program needs an admin privilege... will get back to you once fix is available.

**Comment by minanagehsalalma** [comment]
Which part require admin privileges? It should work fine without it !

**Comment by WarenGonzaga** [comment]
@minanagehsalalma in your copy open the .bat file and remove line 36 to 42 and 48 to 66 and it runs it as admin. It should work... but I'm working on a fix so you don't have to do this in the next version.

**Comment by minanagehsalalma** [comment]
"it runs it as admin."

Without me running it as administrator?!

**Comment by WarenGonzaga** [comment]
@minanagehsalalma nope... it was a typo... "and run it as admin."

**Comment by minanagehsalalma** [comment]
Back to point zero... Netsh doesn't require admin privileges for it to
work...why does your tool require it ?

**Comment by WarenGonzaga** [comment]
Some part of it the program requires admin privileges... I'm currently working on it... and if admin privileges not really needed I will remove it.

**Comment by rewind99** [comment]
This is not a Tool for Users instead its for Admins - for me its totally ok to do it with admin rights It would be nice to enter my credentials anywhere in the script so i didnt have to type em in.

**Comment by WarenGonzaga** [comment]
@rewind99 thanks... but as per checking... the program still works even without admin rights... so the admin checking part is kind of useless... I might remove it... and change the program for users. Let me work on the fix...

**Comment by rewind99** [comment]
At least its always possible to right click and run as admin...

**Comment by WarenGonzaga** [comment]
@rewind99 and @minanagehsalalma this issue has been fixed! Check release 2.5.0
https://github.com/WarenGonzaga/wifi-passview/releases/tag/2.5.0

Let me know if you need any help... I'm closing this now...

**Comment by minanagehsalalma** [comment]
> Some part of it the program requires admin privileges.

@WarenGonzaga  which part exactly that requires that all the options in netsh works without admin privileges.

@rewind99 why do you think this a tool for admins ? 
It should be for everyone not just admins !

**Comment by minanagehsalalma** [comment]
@WarenGonzaga thanks for the update mate ;) really appreciate it
