### ISSUE TITLE
dedicated homepage for the project

### ISSUE THREAD

**Issue by warengonzaga** [WarenGonzaga/wifi-passview#26]
I decided to create a dedicated homepage for this project. If anyone wants to help please reply to this issue.

**Comment by WarenGonzaga** [comment]
What's the tech stack you are planning to use? @angelofallars

**Comment by angelofallars** [comment]
@WarenGonzaga No clue so far. Right now I can work on just making the basic HTML/CSS landing page with all the necessary information. What's your idea on the tech stack? I could potentially use Python for the backend if needed.

**Comment by angelofallars** [comment]
> As much as possible I prefer serverless tech stack. More static as possible. You can try looking at this [repo](https://github.com/warengonzaga/daisy.js).

To be honest I have no clue about all these. I am still very much a beginner in web development. 😅

What I can do now is to start making the let's say `index.html` landing page file with CSS styling (light or dark theme). You can tell me what content/text should I put in the page and any links like the repo link and the donation links. We can figure out the tech stack after this.
