### ISSUE TITLE
Switch from gulp to npm scripts

### ISSUE THREAD

**Issue by dahfool** [WarenGonzaga/wifi-passview#3]
Hi Waren, i cannot test because i am on a mac but i advise you to move away from gulp to just using npm. Task like copying, rename ... can be done with node(npm) and help to decrease dependencies.

**Comment by WarenGonzaga** [comment]
I'm agree with that... animate.css v4 runs with postcss with plain npm setup... will move to npm ;), Thanks for your suggestion.

**Comment by dahfool** [comment]
> I'm agree with that... animate.css v4 runs with postcss with plain npm setup... will move to npm ;), Thanks for your suggestion.

For CI try CircleCI rather than Travis

**Comment by WarenGonzaga** [comment]
> > I'm agree with that... animate.css v4 runs with postcss with plain npm setup... will move to npm ;), Thanks for your suggestion.
> 
> For CI try CircleCI rather than Travis

I will look into Circle CI do you have experience with that?

**Comment by dahfool** [comment]
> > > I'm agree with that... animate.css v4 runs with postcss with plain npm setup... will move to npm ;), Thanks for your suggestion.
> > 
> > 
> > For CI try CircleCI rather than Travis
> 
> I will look into Circle CI do you have experience with that?

Yes, very easy to integrate check this repo https://github.com/dahfool/pati as a simple example.

**Comment by WarenGonzaga** [comment]
> > > > I'm agree with that... animate.css v4 runs with postcss with plain npm setup... will move to npm ;), Thanks for your suggestion.
> > > 
> > > 
> > > For CI try CircleCI rather than Travis
> > 
> > 
> > I will look into Circle CI do you have experience with that?
> 
> Yes, very easy to integrate check this repo https://github.com/dahfool/pati as a simple example.

Thank you mentor... I will probably add this by version 3.

**Comment by WarenGonzaga** [comment]
@dahfool I guess I can't move right now to NPM due to there is some part of project that needs the help of gulp... if you can convert it to NPM a PR from you would be a great help!
