### ISSUE TITLE
doesn't work on Chinese os

### ISSUE THREAD

**Issue by DoingDog** [WarenGonzaga/wifi-passview#38]
![image](https://user-images.githubusercontent.com/72430078/151654215-47dd8eed-0447-4e7c-a385-6203bc8f58c5.png)
![image](https://user-images.githubusercontent.com/72430078/151654223-1a58ec87-44c9-415a-b9fd-6b3dde7bdca7.png)

it doesn't work on my pc
nothing is saved in Automated mode
env: win10 LTSC language:simplified Chinese

**Comment by DoingDog** [comment]
and I wrote another one
https://github.com/DoingDog/wifi-pwd-win

**Comment by DoingDog** [comment]
for there is a SSID with spaces in its name
fully HUAWEI P30 Pro
and it shows only "Pro"

**Comment by WarenGonzaga** [comment]
what would be the fix for this? @DoingDog on your version?

**Comment by DoingDog** [comment]
> what would be the fix for this? @DoingDog on your version?

mine selects the response of netsh (3rd and 18th line of SSID and pwd) row by row first ，and then extract what after the ":" 

like this,reading the 3rd line in 3.txt

set skp=1
set/a pwa=%skp%*20-18
for /f "skip=%pwa% tokens=* delims= " %%i in (3.txt) do (
set wfn=%%~i
goto :out1
)
:out1

**Comment by WarenGonzaga** [comment]
> > what would be the fix for this? @DoingDog on your version?
> 
> mine selects the response of netsh (3rd and 18th line of SSID and pwd) row by row first ，and then extract what after the ":"
> 
> like this,reading the 3rd line in 3.txt
> 
> set skp=1 set/a pwa=%skp%_20-18 for /f "skip=%pwa% tokens=_ delims= " %%i in (3.txt) do ( set wfn=%%~i goto :out1 ) :out1

a good workaround for specific targeting exact words, which is nice! Your fix will not apply across the device I think. I'll merge this issue to this #16 since it has the same exact issue on wording and language. I'm currently improving the project.
