### ISSUE TITLE
Support for other languages (Spanish)

### ISSUE THREAD

**Issue by alexynior28** [WarenGonzaga/wifi-passview#4]
Congratulations! The program is great, but it doesn't work for Spanish language. I was reviewing it and the findstr command is the problem, because the characters are in another language.

* You will not find the password because findstr / c: "Key Content" is not in Spanish language

En Inglés:
    Key Content  : XXXXXXX
En español:
    Contenido de la clave  : XXXXXXX

**Comment by WarenGonzaga** [comment]
Hi @alexynior28, thank you for your suggestion... I'm happy to work on your suggested feature to support other language. Is this the exact translation of "Key Content" to Spanish? "Contenido de la clave" I just wanna make sure...

**Comment by alexynior28** [comment]
Yes, I will show you an exact output so you can be guided:

*I think we will also have to modify the part of: findst "all"

`Perfil ALEXYNIOR en la interfaz Wi-Fi:
=======================================================================

Aplicado: Perfil de todos los usuarios

Información del perfil
----------------------
    Versión                : 1
    Tipo                   : LAN inalámbrica
    Nombre                 : ALEXYNIOR 
    Opciones de control    :
        Modo de conexión : conectar automáticamente
        Difusión de red  : conectarse solo si esta red está difundiendo
        Cambio automático: no cambiar a otras redes
        Selección aleatoria de dirección MAC: deshabilitada

Configuración de conectividad
-----------------------------
    Número de SSID        : 1
    Nombre de SSID       : "ALEXYNIOR"
    Tipo de red           : Infraestructura
    Tipo de radio          : [ Cualquier tipo de radio ]
    Extensión de proveedor         : no está presente

Configuración de seguridad
--------------------------
    Autenticación                  : WPA2-Personal
    Cifrado                        : CCMP
    Autenticación                  : WPA2-Personal
    Cifrado                        : GCMP
    Clave de seguridad                         : Presente
    Contenido de la clave  : 12345!"#

Configuración de costos
-------------
    Costo                   : Sin restricciones
    Congestionado              : No
    A punto de alcanzar el límite de datos: No
    Límite de datos superado        : No
    Itinerancia                : No
    Origen de costo            : Predeterminado
`
![GITHUB](https://user-images.githubusercontent.com/19245743/80035673-091c8600-84b6-11ea-8e5c-1ae71fe81de3.PNG)

**Comment by WarenGonzaga** [comment]
@alexynior28 thank you for your help... I will work on it by weekend.

**Comment by alexynior28** [comment]
Very thank you

**Comment by WarenGonzaga** [comment]
@alexynior28 kindly check the dev build for 2.8.0 there is a temporary language support. Check the config file and replace with corresponding language for spanish.

```json
"langall":"All",
"langkeycontent":"Key Content"
``` 

Just change the value and let me know if works so I can merge this fix to the master branch.

**Comment by alexynior28** [comment]
Hi, Thanks

I checked it and it works fine (IN MANUAL MODE) when I modify the variables in the wifi-passview-v2.8.0.bat file.

set langall=All users
set langkeycontent=Content of the key

*But, In Automatic Mode, it doesn't save the key to me.

However, when I put the string in the variables of the config.json file I get an error when executing the core.bat file (FINDSTR: an argument is missing after /c) . I bought that FINDSTR is correct, however I don't know why the error is.

**I'm reviewing what may have gone wrong

**Comment by WarenGonzaga** [comment]
@alexynior28 I guess wrong... this is how to generate the file from the config...

1. Edit the config...
```json
{
    "filename":"wifi-passview",
    "title":"WiFi Passview",
    "version":"v2.8.0",
    "status":"Karin",
    "dev":"Waren Gonzaga",
    "description":"An open source batch script based program that can recover your WiFi Password easily in seconds.",
    "uicolor":"a",
    "infouicolor":"b",
    "erruicolor":"c",
    "langall":"todos",
    "langkeycontent":"Contenido de la clave"
}
```

2. Now go to the terminal and type: ``gulp``
3. A new build will appear... and ready to use...

Please try that one... you have to replace the values of ``langall`` and ``langkeycontent`` in config file in your language.

**Comment by alexynior28** [comment]
Done, it works in manual mode, but in automatic mode it doesn't save the key.

![cred](https://user-images.githubusercontent.com/19245743/80898631-54f7d800-8ccb-11ea-9376-f3ba8dc959f1.PNG)

**Comment by alexynior28** [comment]
The words used in Spanish were:
    "langall":"Todos los usuarios",
    "langkeycontent":"Contenido de la clave"

![prod_ma](https://user-images.githubusercontent.com/19245743/80898691-f41ccf80-8ccb-11ea-8550-b0e0fe47daec.PNG)


*The word "Todos" is ambiguous in Spanish, that's why it works with "Todos los usuarios".

**Comment by WarenGonzaga** [comment]
@alexynior28 I found the issue... helper.bat this is the issue... the program will be translated correctly except this one. Try to add _REM_ prefix in the line 118 of .bat file.

```batch
118 REM start helper.bat
```

Like that one... and run the program then send here the content of helper.bat you'll see what I mean...

**Comment by WarenGonzaga** [comment]
@alexynior28 additionally add _REM_ to line 122 like below...

```batch
122 REM del /q helper.bat
```

**Comment by alexynior28** [comment]
Excellent, now it works. Confirmed.

Perhaps another suggestion would be to translate the steps to be carried out in the program (its indications). But I will explain it in EsGeeks soon. 

Thank you.

**Comment by WarenGonzaga** [comment]
@alexynior28 don't worry, I will find a way to translate the helper.bat from one file. Or modify the generation process... I will need time to restructure the build since I'm adding language support.

**Comment by alexynior28** [comment]
It's okay. Great, thanks.

**Comment by ipodipad** [comment]
@WarenGonzaga 
@alexynior28 

I think command below would work fine regardless of localization of netsh.exe

```bash
netsh wlan show profiles ILOVELG key=clear | findstr /N /R /C:":" | findstr 33
```

result
```bash


C:\WINDOWS\system32>netsh wlan show profiles ILOVEYJ key=clear | findstr /N /R /C:":"
2:Wi-Fi 인터페이스의 ILOVEYJ 프로필:
5:적용됨: 모든 사용자 프로필
9:    버전                : 1
10:    유형                   : 무선 LAN
11:    이름                   : ILOVEYJ
12:    제어 옵션        :
13:        연결 모드    : 자동 연결
14:        네트워크 브로드캐스트: 이 네트워크가 브로드캐스트 중인 경우에만 연결
15:        자동 전환         : 다른 네트워크로 전환 안 함
16:        MAC 임의 지정  : 사용 안 함
20:    SSID 개수        : 1
21:    SSID 이름              : "ILOVEYJ"
22:    네트워크 종류           : 인프라
23:    Radio 유형             : [ 모든 무선 유형 ]
24:    공급업체 확장          : 없음
28:    인증         : WPA2-개인
29:    암호                 : CCMP
30:    인증         : WPA2-개인
31:    암호                 : GCMP
32:    보안 키           : 있음
33:    키 콘텐츠            : yourpassword
37:    비용                   : 고정
38:    정체됨              : 아니요
39:    데이터 제한에 근접: 아니요
40:    데이터 제한 초과        : 아니요
41:    로밍                : 아니요
42:    비용 출처            : 사용자
```

```

C:\WINDOWS\system32>netsh wlan show profiles ILOVELG key=clear | findstr /N /R /C:":" | findstr 33
33:    키 콘텐츠            : yourpassword
````

**Comment by WarenGonzaga** [comment]
Hi @alexynior28 can you try the suggested fix by @ipodipad and let me know your findings... thank you!

**Comment by WarenGonzaga** [comment]
Hi @ipodipad and @alexynior28 thank you again for your report and approach to this issue. I manage to solve the issue by following the brilliant idea from @ipodipad will merge the update today and release the version 4 by tomorrow.

**Comment by alexynior28** [comment]
Yes, that command also works correctly for Spanish :)

**Comment by WarenGonzaga** [comment]
@alexynior28 can you try the v4 on dev branch? I already build that one... preparing for launching.

**Comment by WarenGonzaga** [comment]
@alexynior28 please confirm the fix... so I can submit this to media partners to update their posts for the new version.

**Comment by alexynior28** [comment]
Hi, it works fine in manual mode. In automatic mode it captures the profile, but not the password.

![Captura](https://user-images.githubusercontent.com/19245743/86552307-39988b80-bf0d-11ea-86da-87f3c168556c.PNG)

**Comment by WarenGonzaga** [comment]
Got it @alexynior28! I will investigate on automatic mode... thank you for responding and helping me to improve the tool.

**Comment by alexynior28** [comment]
Great, you're welcome. :)

**Comment by WarenGonzaga** [comment]
@alexynior28 can you try the latest build on commit #12 thank you and let me know if it fix the automated mode.

**Comment by alexynior28** [comment]
Hi, it still doesn't work, it doesn't store the password

![Captura](https://user-images.githubusercontent.com/19245743/86553843-78304500-bf11-11ea-8b6d-9195bad8010e.PNG)

**Comment by WarenGonzaga** [comment]
@alexynior28 did you run this program as administrator? or not?

**Comment by alexynior28** [comment]
Hi, when I run it as an administrator for some reason it doesn't create the creds.txt file

**Comment by WarenGonzaga** [comment]
@alexynior28 alright... I will implement the features first then let's fix the language support... @ipodipad can you try the latest build on your machine? Let's see if there is difference...

**Comment by WarenGonzaga** [comment]
Hi @alexynior28, done implementing the features... can you follow the pattern below?
Open the tool, 5 > 1 > 8 > 1 > 5 > 3 and take a screenshot... in my end it is working correctly... please help us @ipodipad to confirm if the latest build fixes the automated issues in new version.

**Comment by WarenGonzaga** [comment]
Hi guys @alexynior28 and @ipodipad I'm gonna close this... please feel free to open the issue if it still not fix the issue in language compatibility thank you!

**Comment by alexynior28** [comment]
Thank you, however I still get the same screenshot as the previous one.

**Comment by WarenGonzaga** [comment]
Hi @alexynior28 thank you for the response... however in my end it works perfectly... but I will conduct more investigation why is not working on your side. Waiting for @ipodipad feedback to confirm the issue.

**Comment by WarenGonzaga** [comment]
Merging this issue to #14
